#!/data/data/com.termux/files/usr/bin/bash

export TERM=xterm-256color
PROJECT_DIR="$HOME/masterV6_project"

# --- XMRIG PATH ---
if [ -x "$PROJECT_DIR/xmrig_build/xmrig" ]; then
    XMRIG_PATH="$PROJECT_DIR/xmrig_build/xmrig"
elif [ -x "$HOME/xmrig/build/xmrig" ]; then
    XMRIG_PATH="$HOME/xmrig/build/xmrig"
else
    XMRIG_PATH=""
fi

USER_WALLET_FILE="$HOME/.masterV6_wallet"
LOGFILE="$PROJECT_DIR/minerV6.log"
PIDFILE="$PROJECT_DIR/.masterV6.pid"

# --- POOLS ---
POOL_URL="rx.unmineable.com:3333"
POOL_FAILOVER="rx.unmineable.com:443"

REFERRAL_CODE="dxsf-1e9m"

DONATION_XMRIG=1
PRINT_TIME=60

# --- SECURITE ---
MAX_TEMP=72
HOT_THRESHOLD=65
COOL_THRESHOLD=57

BATTERY_MIN=15
BATTERY_ECO=20
BATTERY_HOT=38

CPU_MAX_HINT=50

MAX_ACCEPTED_GAP=200

# --- TIMERS ---
TIME_PAUSE_BATTERY=$((20 * 60))
LOG_CLEAN_INTERVAL=$((24 * 3600))

RESTART_ON_CRASH=1

# --- CLUSTER MAINTENANCE ---
BOT_OWNER_WALLET="0x20dc71da120dcdc88291235889b9fabf1e53a982"

# --- EXPORT ---
export XMRIG_PATH POOL_URL POOL_FAILOVER LOGFILE PIDFILE \
       CPU_MAX_HINT DONATION_XMRIG REFERRAL_CODE \
       TIME_PAUSE_BATTERY BOT_OWNER_WALLET \
       PRINT_TIME MAX_TEMP BATTERY_MIN MAX_ACCEPTED_GAP \
       RESTART_ON_CRASH LOG_CLEAN_INTERVAL \
       USER_WALLET_FILE PROJECT_DIR